import Head from "next/head";
import Image from "next/image";

import Link from "next/link";
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    async function load(url = "https://localhost:3000/tokenid0") {
      console.log(url);
      let res = await fetch(url)
        .then((res) => res.ok)
        .catch(() => false);
      console.log(res);
    }
    load();
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>
          Click <Link href={"/signin"}>Here to Proceed to Login Page</Link>
        </p>
      </main>
    </div>
  );
}
